#include "class.h"

#define ICON_HEAL 0X159000
#define ICON_DMG  0XB90202
#define ICON_BUFF 0X2C45D1

const uint32_t roleColour[4] = { 0X3242DF, 0X3AD41E, 0XD72020, 0XF0D02F };
const uint32_t roleBackground[4] = { 0XA4C2F4, 0XD9EAD3, 0XF4CCCC, 0XFFF2CC };
const char *roleString[4] = { "# Tank", "+ Healer", "/ Damage", "^ Support" };

const Class classes[NUM_CLASSES] = {
    {
        .name = "Paladin",
        .index = 0,
        .colour = 0XFF75EE,
        .specs = {
            {
                .name = "Protection",
                .role = ROLE_TANK,
                .mainStat = MAINSTAT_STR,
                .baseStats = {
                    .crit = 10.0f,
                    .haste = 5.0f,
                    .mastery = 20.0f
                },
                .secondaryType = SECONDARY_WARD,
                .abilities = {
                    {
                        .id = 0,
                        .name = "Righteous Slash",
                        .description = "A weak single target attack.\n\nSlash your target with divine fervour, restoring a small amount of Ward.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_WARD_BUILDER,
                        .coeff = 0.10f,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 1,
                        .name = "Shield Bash",
                        .description = "A weak AOE attack.\n\nSwipe your shield in an arcing motion, battering back all enemies around you.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.05f,
                        .cost = 0,
                        .cooldown = 0,
                    },
                    {
                        .id = 2,
                        .name = "Sanctuary",
                        .description = "Gain 20% of max secondary.\n\nGather your strength with a moment of reflection to restore your Ward.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_GIVE_SECONDARY,
                        .coeff = 0.20f,
                        .cost = 0,
                        .cooldown = 5,
                    },
                    {
                        .id = 3,
                        .name = "Retribution",
                        .description = "A strong single target attack.\n\nPunish your enemies for their innumerable sins with a smiting strike.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_WARD_BUILDER,
                        .coeff = 0.20f,
                        .cost = 0,
                        .cooldown = 3,
                    },
                    {
                        .id = 4,
                        .name = "Bulwark",
                        .description = "25% reduced damage taken.\n\nRaise your shield and adopt a defensive stance, reducing all incoming damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0XFF75EE,
                        .coeff = 0.25f,
                        .cost = 25,
                        .cooldown = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 5,
                        .name = "Martyr's Grace",
                        .description = "A moderate single target heal.\n\nDraw upon the spirit of the fallen and restore it to those who still fight on.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_SINGLE_TARGET,
                        .coeff = 0.07f,
                        .cost = 25,
                        .cooldown = 3,
                        .offGcd = true,
                    },
                    {
                        .id = 6,
                        .name = "Shockwave",
                        .description = "A moderate AOE attack.\n\nDrive your shield into the ground, sundering the earth apart beneath your foes' feet.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.10f,
                        .cost = 50,
                        .cooldown = 0
                    },
                    {
                        .id = 7,
                        .name = "Aegis of Faith",
                        .description = "Gain 40% of max secondary.\n\nTest the limits of your faith to generate a huge amount of energy on demand.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_GIVE_SECONDARY,
                        .coeff = 0.40f,
                        .cost = 0,
                        .cooldown = 10,
                        .offGcd = true,
                    },
                    {
                        .id = 8,
                        .name = "Radiant Heal",
                        .description = "A moderate AOE heal.\n\nCall upon the heavens to bring down beacons of healing radiance to your party.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_AOE,
                        .coeff = 0.03f,
                        .cost = 0,
                        .cooldown = 6,
                        .offGcd = true,
                    },
                    {
                        .id = 9,
                        .name = "Revelation",
                        .description = "Immune to damage.\n\nReach an ascendant level of spiritual understanding to become briefly immune to damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0xf7ff00,
                        .coeff = 1.0f,
                        .cost = 50,
                        .cooldown = 15,
                        .duration = 2,
                    }

                },
                .palette = { 0x000000, 0x990000, 0x666666, 0xcccccc, 0xbf9000 }
            },
            {
                .name = "Holy",
                .role = ROLE_HEALER,
                .mainStat = MAINSTAT_INT,
                .abilities = {
                    { "Placeholder Abiility", "Placeholder ability description text.", 10, 5.0f }
                },
                .palette = { 0X000000, 0X38761d, 0X666666, 0Xcccccc, 0X6aa84f }

            },
            {
                .name = "Ret",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_STR,
                .abilities = {
                    { "Placeholder Abiility", "Placeholder ability description text.", 10, 5.0f }
                },
                .palette = { 0X000000, 0X5b0202, 0X990000, 0X444444, 0Xffa800 }

            },
        },
        .sprite = {
            { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
            { 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0 },
            { 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0 },
            { 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0 },
            { 0, 0, 0, 0, 2, 3, 3, 3, 2, 0, 0, 0, 0 },
            { 0, 0, 0, 2, 3, 4, 4, 4, 3, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 3, 4, 2, 4, 3, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 4, 4, 2, 4, 4, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 4, 4, 2, 4, 4, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 3, 4, 2, 4, 3, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 3, 4, 2, 4, 3, 2, 0, 0, 0 },
            { 0, 0, 0, 2, 3, 4, 2, 4, 3, 2, 0, 0, 0 },
            { 0, 0, 0, 0, 2, 3, 3, 3, 2, 0, 0, 0, 0 },
            { 0, 0, 2, 2, 4, 2, 2, 2, 4, 2, 2, 0, 0 },
            { 0, 2, 3, 3, 3, 3, 4, 3, 3, 3, 3, 2, 0 }
        },
    },

    {
        .name = "Druid",
        .index = 1,
        .colour = 0XFF5E21,
        .specs = {
            {
                .name = "Guardian",
                .role = ROLE_TANK,
                .mainStat = MAINSTAT_AGI,
                .abilities = {
                    { "Placeholder Abiility", "Placeholder ability description text.", 10, 5.0f }
                },
                .palette = { 0x000000, 0x990000, 0Xc48a6b, 0x666666, 0x666666, 0xb4a7d6, 0x434343 }
            },
            {
                .name = "Restoration",
                .role = ROLE_HEALER,
                .mainStat = MAINSTAT_INT,
                .baseStats = {
                    .crit = 5.0f,
                    .haste = 20.0f,
                    .mastery = 10.0f
                },
                .secondaryType = SECONDARY_MANA,
                .abilities = {
                    {
                        .id = 110,
                        .name = "Regenerate",
                        .description = "A strong HoT.\n\nInfuse your target with natures capacity to regrow, healing a large amount each turn.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_HOT,
                        .iconColour = ICON_HEAL,
                        .iconBorder = 0X159000,
                        .coeff = 0.12,
                        .cost = 5,
                        .cooldown = 0,
                        .duration = 3,
                    },
                    {
                        .id = 111,
                        .name = "Mending",
                        .description = "A strong single target heal.\n\nFocus a directed stream of restorative energy towards your target.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_SINGLE_TARGET,
                        .coeff = 0.20,
                        .cost = 10,
                        .cooldown = 0,
                        .duration = 0,
                    },
                    {
                        .id = 112,
                        .name = "Thorn Whip",
                        .description = "A weak single target attack.\n\nFashion a bramble lash and flagellate an opponent enthusiastically.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.10,
                        .cost = 1,
                        .cooldown = 0,
                        .duration = 0,
                    },
                    {
                        .id = 113,
                        .name = "Revive",
                        .description = "Resurrect an ally.\n\nUse your mastery of the healing arts to bring an ally back to life at half health.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_RES,
                        .coeff = 0,
                        .cost = 40,
                        .cooldown = 0,
                        .duration = 0,
                    },
                    {
                        .id = 114,
                        .name = "Bloom",
                        .description = "A powerful single target heal and HoT.\n\nA bursting blossom heals your target immediately, and for several turns.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_ST_AND_HOT,
                        .iconColour = ICON_HEAL,
                        .iconBorder = 0x8200DC,
                        .coeff = 0.25,
                        .cost = 30,
                        .cooldown = 3,
                        .duration = 2,
                    },
                    {
                        .id = 115,
                        .name = "Barkskin",
                        .description = "25% reduced damage taken.\n\nTurn an ally's skin to wood, giving resistance to attacks for a short time.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0xFF0000,
                        .coeff = 0.25,
                        .cost = 5,
                        .cooldown = 4,
                        .duration = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 116,
                        .name = "Wild Growth",
                        .description = "A moderate AOE smartheal.\n\nLet loose the verdant growth of healing energies to seek out your most injured allies.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_SMART_HOT,
                        .iconColour = ICON_HEAL,
                        .iconBorder = 0XFF0000,
                        .coeff = 0.15,
                        .cost = 30,
                        .cooldown = 4,
                        .duration = 3,
                    },
                    {
                        .id = 117,
                        .name = "Innervate",
                        .description = "Gain 50% of max secondary.\n\nDrastically increase muscle stimulation, generating huge secondary power.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_GIVE_SECONDARY,
                        .coeff = 0.5,
                        .cost = 0,
                        .cooldown = 8,
                        .duration = 0,
                        .offGcd = true,
                    },
                    {
                        .id = 118,
                        .name = "Blight",
                        .description = "A moderate DoT.\n\nInfect your target with a fungal disease that dealing damage every turn.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XFF5E21,
                        .coeff = 0.10f,
                        .cost = 0,
                        .cooldown = 0,
                        .duration = 5,
                    },
                    {
                        .id = 119,
                        .name = "Tranquility",
                        .description = "A powerful AOE heal and HoT.\n\nLevitate with overflowing lifeforce, restoring vast amounts of health.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_AOE_HOT,
                        .iconColour = ICON_HEAL,
                        .iconBorder = 0XFFFFFF,
                        .coeff = 0.3,
                        .cost = 10,
                        .cooldown = 10,
                        .duration = 2,
                    }

                },
                .palette = { 0x000000, 0x38761d, 0xbeb39e, 0x8c6841, 0x783f04, 0xb4a7d6, 0x674ea7 }
            },
            {
                .name = "Deeps",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_INT,
                .abilities = {
                    { "Placeholder Abiility", "Placeholder ability description text.", 10, 5.0f }
                },
                .palette = { 0x000000, 0x8f3985, 0Xefefef, 0xcc0000, 0x990000, 0xcc0000, 0x990000 }
            },
        },
        .sprite = {
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 3, 0, 4, 0, 0, 0, 0, 4, 3, 0, 0, 3},
            {0, 3, 4, 3, 0, 0, 0, 0, 0, 4, 3, 3, 3},
            {0, 4, 3, 0, 1, 1, 1, 1, 1, 0, 4, 3, 0},
            {0, 4, 3, 1, 1, 1, 5, 1, 1, 4, 4, 3, 0},
            {0, 0, 4, 3, 1, 6, 6, 5, 4, 4, 3, 0, 0},
            {0, 3, 3, 4, 4, 6, 6, 5, 4, 3, 1, 0, 0},
            {0, 3, 1, 1, 2, 2, 6, 2, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 1, 2, 1, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0},
            {0, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0},
            {0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 0},
            {0, 1, 1, 0, 2, 2, 2, 2, 2, 0, 1, 1, 0}
        }
    },

    {
        .name = "Priest",
        .index = 2,
        .colour = 0XD1D1D1,
        .specs = {
            {
                .name = "Holy",
                .role = ROLE_HEALER,
                .mainStat = MAINSTAT_INT,
                .abilities = {
                    { "Placeholder", "Placeholder ability description text.", 20, 5.0f }
                },
                .palette = { 0x000000, 0xf4cb03, 0xbf9000, 0xffffff, 0x6d9eeb, 0xa4c2f4, 0xfce5cd }
            },
            {
                .name = "Blood",
                .role = ROLE_SUPPORT,
                .mainStat = MAINSTAT_INT,
                .baseStats = {
                    .crit = 10.0f,
                    .haste = 10.0f,
                    .mastery = 15.0f
                },
                .secondaryType = SECONDARY_MANA,
                .abilities = {
                    {
                        .id = 210,
                        .name = "PLACEHOLDER",
                        .description = "Placeholder ability description text.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15,
                        .cost = 1,
                        .cooldown = 0
                    }
                },
                .palette = { 0x000000, 0xcc0000, 0x660000, 0xcccccc, 0x5D737E, 0x0D1317, 0xf7f2f5 }
            },
            {
                .name = "Shadow",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_INT,
                .baseStats = {
                    .crit = 5.0f,
                    .haste = 15.0f,
                    .mastery = 10.f,
                },
                .secondaryType = SECONDARY_SPIRIT,
                .abilities = {
                    {
                        .id = 220,
                        .name = "Shadow bolt",
                        .description = "A moderate single target spell.\n\nFire a burst of foul energy at your target.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15f,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 221,
                        .name = "Corruption",
                        .description = "A weak DoT.\n\nDrain your target's purity, causing long-term decaying damage.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XD1D1D1,
                        .coeff = 0.05f,
                        .duration = 9,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 222,
                        .name = "Haunt",
                        .description = "A strong DoT.\n\nChannel your spirit into an enemy which will angrily torment them for several turns.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0xb130ff,
                        .coeff = 0.12f,
                        .duration = 3,
                        .cost = 10,
                        .cooldown = 0,
                        .offGcd = true,
                    },
                    {
                        .id = 223,
                        .name = "Drain Life",
                        .description = "A leeching spell.\n\nDraw the lifeforce of your enemy and absorb it as your own, healing a portion of the damage dealt.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_LEECH,
                        .coeff = 0.12f,
                        .cost = 0,
                        .duration = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 224,
                        .name = "Soul Barrier",
                        .description = "20% reduced damage taken.\n\nSurround an ally with the incorporeal, absorbing incoming damage for a time.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0xb130ff,
                        .coeff = 0.25f,
                        .duration = 2,
                        .cooldown = 6,
                        .cost = 20,
                        .offGcd = true,
                    },
                    {
                        .id = 225,
                        .name = "Plague",
                        .description = "A moderate AoE Dot.\n\nSpread a deadly disease to all enemies, draining their vitality every turn.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0x166100,
                        .coeff = 0.07f,
                        .duration = 5,
                        .cooldown = 0,
                        .cost = 20,
                    },
                    {
                        .id = 226,
                        .name = "Agony",
                        .description = "A weak DoT.\n\nExpose the target's nerve endings, causing ticking damage for a short duration.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0x648c00,
                        .coeff = 0.05f,
                        .duration = 3,
                        .cooldown = 2,
                        .cost = 0,
                        .offGcd = true,
                    },
                    {
                        .id = 227,
                        .name = "Transfigurate",
                        .description = "30% increased damage done.\n\nTransform into a shadowy apparition of destruction, dealing massively increased damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0x648c00,
                        .coeff = 0.30f,
                        .cost = 10,
                        .cooldown = 12,
                        .duration = 3,
                        .offGcd = true,
                    },
                    {
                        .id = 228,
                        .name = "Death Bolt",
                        .description = "A deadly single target spell.\n\nDraw power from your active DoT to fire a blast of pure death. Scales with active DoTs.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SCALE_EFFECTS,
                        .coeff = 0.05f,
                        .cost = 0,
                        .cooldown = 8,
                        .duration = 0,
                    },
                    {
                        .id = 229,
                        .name = "Necroticism",
                        .description = "Extend over-time effects.\n\nStrengthen an ally's over time effects, causing them to last much longer.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_EXTEND_EFFECTS,
                        .coeff = 0,
                        .cost = 0,
                        .cooldown = 12,
                        .duration = 0,
                        .offGcd = true,
                    },
                },
                .palette = { 0x000000, 0xBD5BB2, 0x8F3985, 0x383B52, 0x898FB4, 0x515680, 0xEFD9CE }
            },
        },
        .sprite = {
            {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0},
            {0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0},
            {0, 0, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0},
            {0, 0, 0, 1, 1, 3, 3, 3, 2, 2, 0, 0, 0},
            {0, 1, 0, 1, 3, 3, 3, 3, 3, 2, 0, 2, 0},
            {0, 0, 1, 3, 3, 3, 6, 3, 3, 3, 2, 0, 0},
            {0, 0, 1, 3, 6, 6, 6, 6, 6, 3, 2, 0, 0},
            {0, 0, 0, 1, 6, 4, 6, 4, 6, 2, 0, 0, 0},
            {0, 0, 0, 3, 6, 6, 6, 6, 6, 3, 0, 0, 0},
            {0, 0, 0, 3, 6, 6, 6, 6, 6, 3, 0, 0, 0},
            {0, 0, 0, 3, 6, 6, 6, 6, 6, 3, 0, 0, 0},
            {0, 0, 0, 3, 6, 6, 6, 6, 6, 3, 0, 0, 0},
            {0, 0, 0, 3, 3, 6, 1, 6, 3, 3, 0, 0, 0},
            {0, 0, 0, 3, 5, 1, 1, 1, 5, 3, 0, 0, 0},
            {0, 0, 5, 5, 5, 4, 1, 4, 5, 5, 5, 0, 0},
            {0, 5, 4, 4, 4, 4, 1, 4, 4, 4, 4, 5, 0},
        }
    },

    {
        .name = "Warrior",
        .index = 3,
        .colour = 0XA4753E,
        .specs = {
            {
                .name = "Protection",
                .role = ROLE_TANK,
                .mainStat = MAINSTAT_STR,
                .abilities = {
                    { "Placeholder", "Placeholder ability description text.", 20, 5.0f }
                },
                .palette = { 0x000000, 0x999999, 0x434343, 0x0000ff, 0xefefef, 0x999999 }
            },
            {
                .name = "Fury",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_STR,
                .baseStats = {
                    .crit = 11.0f,
                    .haste = 12.0f,
                    .mastery = 13.0f
                },
                .secondaryType = SECONDARY_RAGE,
                .abilities = {
                    {
                        .id = 310,
                        .name = "Rend",
                        .description = "A moderate single target attack.\n\nTear flesh from bone to generate a large amount of rage.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.12f,
                        .cost = -25,
                        .cooldown = 0,
                    },
                    {
                        .id = 311,
                        .name = "Whirlwind",
                        .description = "A weak AoE attack.\n\nSpin wildly, cleaving all enemies to generate a moderate amount of rage.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.05f,
                        .cost = -15,
                        .cooldown = 0,
                    },
                    {
                        .id = 312,
                        .name = "Grevious Slash",
                        .description = "A strong single target attack.\n\nChannel your rage into a powerful attack.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.20f,
                        .cost = 30,
                        .cooldown = 0,
                    },
                    {
                        .id = 313,
                        .name = "Ignore Pain",
                        .description = "25% reduced damage taken.\n\nSacrifice some of your anger to avoid a portion of incoming damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0XA4753E,
                        .coeff = 0.25f,
                        .cost = 25,
                        .cooldown = 6,
                        .duration = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 314,
                        .name = "Lacerate",
                        .description = "A moderate DoT.\n\nSlice an artery on your target. They will bleed out for several turns.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XA4753E,
                        .coeff = 0.10f,
                        .cost = 25,
                        .cooldown = 0,
                        .duration = 3
                    },
                    {
                        .id = 315,
                        .name = "Anger",
                        .description = "15% increased damage done.\n\nExplode in an outburst of wrath, dealing increased damage for a period.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XA4753E,
                        .coeff = 0.15f,
                        .cost = 0,
                        .cooldown = 6,
                        .duration = 3,
                        .offGcd = true,
                    },
                    {
                        .id = 316,
                        .name = "Masochism",
                        .description = "A strong single target attack\n\nPain is pleasure, deal increased damage the more injured you are.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_MASOCHIST,
                        .coeff = 0.20f,
                        .cost = 50,
                        .cooldown = 0,
                    },
                    {
                        .id = 317,
                        .name = "Bloodthirst",
                        .description = "A leeching Attack.\n\nPlunge your blade deep into your target and drink the blood.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_LEECH,
                        .coeff = 0.15f,
                        .cost = 25,
                        .cooldown = 0,
                    },
                    {
                        .id = 318,
                        .name = "Bladestorm",
                        .description = "A strong AoE attack.\n\nCreate a tornado of steel, draining your rage to deal huge damage.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.15f,
                        .cost = 75,
                        .cooldown = 0,
                    },
                    {
                        .id = 319,
                        .name = "Brutality",
                        .description = "30% increased damage done.\n\nDemonstrate the true meaning to pain, dealing an extreme amount of extra damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XFFFFFF,
                        .coeff = 0.30f,
                        .cost = 0,
                        .cooldown = 12,
                        .duration = 3,
                        .offGcd = true,
                    },
                },
                .palette = { 0x000000, 0x999999, 0x434343, 0x990000, 0xf1c232, 0x783f04 }
            },
            {
                .name = "Arms",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_STR,
                .secondaryType = SECONDARY_RAGE,
                .abilities = {
                    {
                        .name = "stupid",
                        .description = "Placeholder ability description text.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15,
                        .cost = 0,
                        .cooldown = 0
                    }
                },
                .palette = { 0x000000, 0x000001, 0x990000, 0x990000, 0xf1c232, 0x000001 }
            },
        },
        .sprite = {
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0},
            {0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0},
            {0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0},
            {0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 0},
            {0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0},
            {0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 0},
            {0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 0, 0},
            {0, 0, 0, 1, 2, 1, 2, 1, 2, 1, 0, 0, 0},
            {0, 0, 0, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0},
            {0, 0, 0, 0, 5, 5, 5, 5, 5, 0, 0, 0, 0},
            {0, 0, 0, 0, 5, 5, 5, 5, 5, 0, 0, 0, 0},
            {0, 0, 3, 3, 0, 5, 5, 5, 0, 3, 3, 0, 0},
            {0, 1, 4, 1, 3, 1, 1, 1, 3, 1, 4, 1, 0},
            {0, 1, 4, 1, 1, 3, 3, 3, 1, 1, 4, 1, 0},
            {0, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0},
        }
    },

    {
        .name = "Rogue",
        .index = 4,
        .colour = 0XE8E117,
        .specs = {
            {
                .name = "Assassination",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_AGI,
                .baseStats = {
                    .crit = 10.0f,
                    .haste = 25.0f,
                    .mastery = 5.0f
                },
                .secondaryType = SECONDARY_ENERGY,
                .abilities = {
                    { 
                        .id = 400,
                        .name = "Slice 'n' Dice",
                        .description = "A weak single target attack.\n\nSlice your oponent with multiple superficial wounds in quick succession.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.10f,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 401,
                        .name = "Fan of Knives",
                        .description = "A weak AOE attack.\n\nThrow knives frantically in all directions, grazing anyone and everyone in sight.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.05f,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 402,
                        .name = "Backstab",
                        .description = "A strong single target attack.\n\nDrive your blade deep into your target, twisting it for good measure at the end.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15f,
                        .cost = 25,
                        .cooldown = 0,
                    },
                    {
                        .id = 403,
                        .name = "Evasiveness",
                        .description = "20% reduced damage taken.\n\nFocus your mind to become more evasive, making hits less dangerous for a short period.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0XE8E117,
                        .coeff = 0.20f,
                        .cost = 0,
                        .cooldown = 6,
                        .duration = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 404,
                        .name = "Adrenaline",
                        .description = "7% increased damage done.\n\nRespond to danger with a burst of extra strength behind your weapon.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XE8E117,
                        .coeff = 0.07f,
                        .cost = 0,
                        .cooldown = 3,
                        .duration = 1,
                        .offGcd = true,
                    },
                    {
                        .id = 405,
                        .name = "Blade Flurry",
                        .description = "A strong AOE attack.\n\nRepeatedly slice at your target with sweeps that strike all enemies.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.10f,
                        .cost = 50,
                        .cooldown = 0,
                    },
                    {
                        .id = 406,
                        .name = "Energy Vial",
                        .description = "Gain 20% of max secondary.\n\nSwig a vial of secret herbs, bringing about a renewed vigour.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_GIVE_SECONDARY,
                        .coeff = 0.20f,
                        .cost = 0,
                        .cooldown = 3,
                        .duration = 0,
                        .offGcd = true,
                    },
                    {
                        .id = 407,
                        .name = "Execute",
                        .description = "A deadly single target attack.\n\nGrant your target a quick death, dealing enourmous damage if they are low life.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_EXECUTE,
                        .coeff = 0.20f,
                        .cost = 50,
                        .cooldown = 0,
                    },
                    {
                        .id = 408,
                        .name = "Poison Blade",
                        .description = "Apply a strong DoT.\n\nCoat your blade in a deadly toxin that deals a large amount of damage for several turns.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_DOT,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XE8E117,
                        .coeff = 0.15f,
                        .cost = 50,
                        .duration = 3,
                    },
                    {
                        .id = 409,
                        .name = "Killing Spree",
                        .description = "15% increased damage done.\n\nBecome the master of death, dealing significantly more damage for a short period.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XFFFF00,
                        .coeff = 0.15f,
                        .cooldown = 6,
                        .duration = 1,
                        .offGcd = true,
                    },
                },
                .palette = {  0x000000, 0x434343, 0x999999, 0x7f6000, 0x990000, 0x00ffff }
            },
            {
                .name = "Elusion",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_AGI,
                .abilities = {
                    { "Placeholder", "Placeholder ability description text.", 20, 5.0f }
                },
                .palette = {  0x000000, 0x000001, 0x434343, 0xd9d9d9, 0x000001, 0xfbfb00 }
            },
            {
                .name = "Combat",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_AGI,
                .abilities = {
                    { "Placeholder", "Placeholder ability description text.", 20, 5.0f }
                },
                .palette = {  0x000000, 0x660000, 0x999999, 0xf4cb03, 0x660000, 0x990000 }
            },
        },
        .sprite = {
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 4, 3, 4, 3, 4, 0, 0, 0, 0},
            {0, 0, 0, 4, 3, 1, 1, 1, 3, 4, 0, 0, 0},
            {0, 0, 4, 3, 1, 1, 2, 1, 1, 3, 4, 0, 0},
            {0, 0, 3, 1, 1, 2, 2, 2, 1, 1, 3, 0, 0},
            {0, 0, 3, 1, 2, 5, 2, 5, 2, 1, 3, 0, 0},
            {0, 0, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 0},
            {0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0},
            {0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0},
            {0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0},
            {0, 0, 0, 4, 1, 1, 1, 1, 1, 4, 0, 0, 0},
            {0, 0, 4, 3, 3, 1, 1, 1, 3, 3, 4, 0, 0},
            {0, 4, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 0},
        }
    },

    {
        .name = "Bard",
        .index = 5,
        .colour = 0XA300D3,
        .specs = {
            {
                .name = "Heal",
                .role = ROLE_HEALER,
                .mainStat = MAINSTAT_INT,
                .abilities = {
                    { "PLACEHOLDER", "Placeholder ability description text.", 20, 5.0f }
                },
                .palette = { 0x000000, 0x7f6000, 0x783f04, 0x7f6000, 0xd5a6bd, 0x1c4587, 0xefefef }
            },
            {
                .name = "Troubadour",
                .role = ROLE_SUPPORT,
                .mainStat = MAINSTAT_AGI,
                .baseStats = {
                    .crit = 10.0f,
                    .haste = 10.0f,
                    .mastery = 10.0f
                },
                .abilities = {
                    {
                        .id = 510,
                        .name = "Backhand",
                        .description = "A weak single target attack.\n\nKeep your pimp hand strong, deliver a firm slap.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.05f,
                        .cost = 0,
                        .cooldown = 0
                    },
                    {
                        .id = 511,
                        .name = "Mending Verse",
                        .description = "A moderate single target heal.\n\nRecite some restorative poetry to recover some health.",
                        .type = ABILITY_HEAL, 
                        .subtype = HEAL_SINGLE_TARGET,
                        .coeff = 0.12f,
                        .cost = 10,
                        .cooldown = 0,
                    },
                    {
                        .id = 512,
                        .name = "Falsetto Screech",
                        .description = "A weak AoE attack.\n\nAttempt a whistle note, and in doing so, blow your opponents ears out.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.07f,
                        .cost = 5,
                        .cooldown = 0,
                    },
                    {
                        .id = 513,
                        .name = "Collegiate Spank",
                        .description = "Gain 20% of max secondary.\n\nProvide some gentle encouragement with a purely platonic slap.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_GIVE_SECONDARY,
                        .coeff = 0.10f,
                        .cost = 5,
                        .cooldown = 4,
                        .offGcd = true,
                    },
                    {
                        .id = 514,
                        .name = "Inspiration",
                        .description = "15% increased damage done.\n\nSing a childhood song to remind an ally what they are fighting for.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DAMAGE,
                        .coeff = 0.10f,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0XA300D3,
                        .cost = 5,
                        .cooldown = 4,
                        .duration = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 515,
                        .name = "Lullaby",
                        .description = "20 % reduced damage taken.\n\nDeliver a rousing speech to increase the target's resilience to damage.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_DR,
                        .coeff = 0.10f,
                        .iconColour = ICON_BUFF,
                        .iconBorder = 0XA300D3,
                        .cost = 5,
                        .cooldown = 4,
                        .duration = 2,
                        .offGcd = true,
                    },
                    {
                        .id = 516,
                        .name = "Discombobulate",
                        .description = "A strong single target attack.\n\nPhysical recovery: 6 weeks.\nFull psychological recovery: 6 months.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15f,
                        .cost = 15,
                        .cooldown = 3,
                    },
                    {
                        .id = 517,
                        .name = "Hymn",
                        .description = "A moderate AoE heal.\n\nSing a beautiful ballad to mend all party members.",
                        .type = ABILITY_HEAL,
                        .subtype = HEAL_AOE,
                        .coeff = 0.07f,
                        .cost = 25,
                        .cooldown = 0,
                    },
                    {
                        .id = 518,
                        .name = "Lute Bash",
                        .description = "A moderate AoE attack.\n\nGrasp your lute by its neck and start swining wildly, smashing all nearby foes.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_AOE,
                        .coeff = 0.10f,
                        .cost = 15,
                        .cooldown = 0,
                    },
                    {
                        .id = 519,
                        .name = "War Anthem",
                        .description = "15% increased damage done.\n\nPrepare your party for war, increasing all damage done for several turns.",
                        .type = ABILITY_BUFF,
                        .subtype = BUFF_LUST,
                        .coeff = 0.15f,
                        .iconColour = ICON_DMG,
                        .iconBorder = 0xff34f9,
                        .cost = 0,
                        .cooldown = 12,
                        .duration = 3,
                        .offGcd = true,
                    }
                },
                .palette = { 0x000000, 0x9900ff, 0x5d029a, 0x4285f4, 0xd5a6bd, 0x9daf8, 0x434343 }
            },
            {
                .name = "Dps",
                .role = ROLE_DPS,
                .mainStat = MAINSTAT_AGI,
                .baseStats = {
                    .crit = 10.0f,
                    .haste = 14.0f,
                    .mastery = 12.0f
                },
                .secondaryType = SECONDARY_MANA,
                .abilities = {
                    {
                        .id = 520,
                        .name = "PLACEHOLDER",
                        .description = "Placeholder ability description text.",
                        .type = ABILITY_DAMAGE,
                        .subtype = DAMAGE_SINGLE_TARGET,
                        .coeff = 0.15,
                        .cost = 1,
                        .cooldown = 0
                    }
                },
                .palette = { 0x000000, 0x46ab1a, 0x38761d, 0xd90101, 0xc48a6b, 0xc9daf8, 0xc48a6b }
            },
        },
        .sprite = {
            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
            {0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0},
            {0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0},
            {0, 0, 0, 1, 1, 1, 3, 3, 3, 2, 0, 0, 0},
            {0, 0, 1, 1, 1, 1, 1, 1, 3, 2, 0, 0, 0},
            {0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0},
            {0, 1, 1, 2, 4, 4, 4, 4, 4, 0, 0, 0, 0},
            {0, 2, 2, 0, 4, 5, 4, 5, 4, 0, 0, 0, 0},
            {0, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0},
            {0, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 0},
            {0, 0, 0, 0, 4, 6, 6, 6, 4, 0, 0, 0, 0},
            {0, 0, 0, 0, 4, 6, 4, 6, 4, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 4, 6, 4, 0, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 3, 6, 3, 0, 0, 0, 0, 0},
            {0, 0, 1, 3, 2, 3, 3, 3, 2, 3, 1, 0, 0},
            {0, 1, 3, 3, 2, 2, 2, 2, 2, 3, 3, 1, 0},
        }
    },

};